development: &default
  adapter: postgresql
  database: fit_bit_integration_development
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: fit_bit_integration_test
